server:
  port: 8662    #port number

spring:    
  application:
    name: zuul-gateway

eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
    instance:
      hostname: localhost

zuul:
  host:
    connect-timeout-millis: 5000000
    socket-timeout-millis: 5000000
  ignoredServices: '*'
  routes:
    employee-service:
      path: /employee/**
      serviceId: employee-service
      stripPrefix: true
    api-gateway:
      path: /service2/**
      serviceId: service2
      stripPrefix: true
 
logging:
  level:
    com.self.sprintboot.learning.apigateway: DEBUG